# web context监听配置
server:
    port: 8080
    servlet:
        context-path: /
spring:
    # 随便加个banner
    banner:
        charset: UTF-8
        location: classpath:banner.txt
    devtools:
        restart:
            enabled: false  #设置是否开启热部署，一般情况不用开启，可使用idea的热加载机制
            additional-paths: src/main/java #重启目录
    # thymeleaf模板引擎
    thymeleaf:
        cache: false        #禁用缓存，防止开发修改后页面不生效
        mode: HTML
        encoding: UTF-8
        servlet:
            content-type: text/html
    # spring-session配置
#    session:
#        store-type: redis
    # redis相关配置
    redis:
        host: 127.0.0.1
        port: 6379
        password: 123456
        timeout: 10000ms        # 连接超时时间（记得添加单位，Duration）
        # Redis默认情况下有16个分片，这里配置具体使用的分片
        # database: 0
        lettuce:
            pool:
                max-active: 8   # 连接池最大连接数（使用负值表示没有限制） 默认 8
                max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
                max-idle: 8     # 连接池中的最大空闲连接 默认 8
                min-idle: 0     # 连接池中的最小空闲连接 默认 0